name: harikrushna_group_rajkot
description: Hotel Booking App for Harikrushna Group.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
cloud_firestore: ^4.17.4
http: ^1.2.1
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  intl: ^0.18.1
 

flutter:
  uses-material-design: true
