name: Build Android APK

on:
  push:
    branches:
      - main  # જ્યારે તમે કોડ સેવ કરો ત્યારે આ રન થશે

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # અથવા તમારું વર્ઝન

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug # ટેસ્ટિંગ માટે ડેબગ APK

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: hotel-app-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
