name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Recreate Android files
        run: flutter create . --project-name=harikrushna_group_rajkot --platforms android

      - name: Fix Android Settings (Firebase Support)
        # આ લાઇન minSdkVersion ને ૨૧ કરશે અને multiDex ચાલુ કરી દેશે
        run: |
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' android/app/build.gradle
          sed -i 's/targetSdkVersion flutter.targetSdkVersion/targetSdkVersion flutter.targetSdkVersion\n        multiDexEnabled true/g' android/app/build.gradle

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hotel-app-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
